Public Module ItemType
    Public Const PlantFiber = "PlantFiber"
    Public Const Stick = "Stick"
    Public Const Rock = "Rock"
    Public Const Twine = "Twine"
    Public Const SharpRock = "SharpRock"
    Public Const Hatchet = "Hatchet"
    Public Const Log = "Log"
    Public Const Hammer = "Hammer"
    Public Const Plank = "Plank"
    Public Const SharpStick = "SharpStick"
    Public Const Grub = "Grub"
    Public Const CookedGrub = "CookedGrub"
    Public Const Clay = "Clay"
    Public Const Charcoal = "Charcoal"
    Public Const UnfiredBrick = "UnfiredBrick"
    Public Const Brick = "Brick"
    Public Const FishingNet = "FishingNet"
    Public Const RawFish = "RawFish"
    Public Const RawFishFilet = "RawFishFilet"
    Public Const FishHead = "FishHead"
    Public Const FishGuts = "FishGuts"
    Public Const Knife = "Knife"
    Public Const Blade = "Blade"
    Public Const CookedFishFilet = "CookedFishFilet"
    Public Const RockFlake = "RockFlake"
End Module
