local M = {}

M.BOARD_COLUMNS = 11
M.BOARD_CENTER_COLUMN = math.floor((M.BOARD_COLUMNS + 1) / 2)
M.BOARD_ROWS = 11
M.BOARD_CENTER_ROW = math.floor((M.BOARD_ROWS + 1) / 2)
M.BOARD_CELL_WIDTH = 8
M.BOARD_CELL_HEIGHT = 8
M.BOARD_WIDTH = M.BOARD_CELL_WIDTH * M.BOARD_COLUMNS
M.BOARD_HEIGHT = M.BOARD_CELL_HEIGHT * M.BOARD_ROWS

M.TILE_HERO = 1

M.TILE_BLANK = 4
M.TILE_NORTH_WALL = 5
M.TILE_EAST_WALL = 6
M.TILE_SOUTH_WALL = 7
M.TILE_WEST_WALL = 8
M.TILE_NORTHEAST_INSIDE_CORNER = 9
M.TILE_SOUTHEAST_INSIDE_CORNER = 10
M.TILE_SOUTHWEST_INSIDE_CORNER = 11
M.TILE_NORTHWEST_INSIDE_CORNER = 12

M.COMMAND_UP = "UP"
M.COMMAND_DOWN = "DOWN"
M.COMMAND_LEFT = "LEFT"
M.COMMAND_RIGHT = "RIGHT"
M.COMMAND_GREEN = "GREEN"
M.COMMAND_RED = "RED"
M.COMMAND_BLUE = "BLUE"
M.COMMAND_YELLOW = "YELLOW"

M.FONT3X5 = "FONT3X5"
M.FONT4X6 = "FONT4X6"
M.FONT5X7 = "FONT5X7"
M.FONT7X7 = "FONT7X7"

M.TILESET_TERRAIN = "TILESET_TERRAIN"
M.TILESET_CHARACTERS = "TILESET_CHARACTERS"
M.TILESET_ITEMS = "TILESET_ITEMS"

M.VIEW_WIDTH = 160
M.VIEW_HEIGHT = 90

return M