local M = {}

M.BOARD_COLUMNS = 11
M.BOARD_CENTER_COLUMN = math.floor((M.BOARD_COLUMNS + 1) / 2)
M.BOARD_ROWS = 11
M.BOARD_CENTER_ROW = math.floor((M.BOARD_ROWS + 1) / 2)
M.BOARD_CELL_WIDTH = 8
M.BOARD_CELL_HEIGHT = 8
M.BOARD_WIDTH = M.BOARD_CELL_WIDTH * M.BOARD_COLUMNS
M.BOARD_HEIGHT = M.BOARD_CELL_HEIGHT * M.BOARD_ROWS

M.TILE_HERO = 1
M.TILE_BLANK = 4

M.COMMAND_UP = "UP"
M.COMMAND_DOWN = "DOWN"
M.COMMAND_LEFT = "LEFT"
M.COMMAND_RIGHT = "RIGHT"
M.COMMAND_GREEN = "GREEN"
M.COMMAND_RED = "RED"

return M