Public Enum Topic
    ItemTypeBlade
    ItemTypeBrick
    ItemTypeCharcoal
    ItemTypeClay
    ItemTypeCookedFishFilet
    ItemTypeCookedGrub
    ItemTypeFishGuts
    ItemTypeFishHead
    ItemTypeFishingNet
    ItemTypeGrub
    ItemTypeKnife
    ItemTypeHammer
    ItemTypeHatchet
    ItemTypeLog
    ItemTypePlank
    ItemTypePlantFiber
    ItemTypeRawFish
    ItemTypeRawFishFilet
    ItemTypeRock
    ItemTypeSharpRock
    ItemTypeSharpStick
    ItemTypeStick
    ItemTypeTwine
    ItemTypeUnfiredBrick

    NavigationDeeds
    NavigationGameMenu
    NavigationInventory
    NavigationMove
    NavigationSkills
    NavigationCraft

    VerbTypeBlade
    VerbTypeBrick
    VerbTypeCharcoalCookingFire
    VerbTypeChop
    VerbTypeCookedFishFilet
    VerbTypeCookedGrub
    VerbTypeCookingFire
    VerbTypeDigGrass
    VerbTypeDigPond
    VerbTypeFishingNet
    VerbTypeForageGrass
    VerbTypeForagePine
    VerbTypeForageRock
    VerbTypeFurnace
    VerbTypeHammer
    VerbTypeHatchet
    VerbTypeKnife
    VerbTypePlank
    VerbTypeRawFishFilet
    VerbTypeSharpRock
    VerbTypeSharpStick
    VerbTypeTwine
    VerbTypeUnfiredBrick
    VerbTypeWait
    VerbTypeFish

    SkillTypeForaging
    SkillTypeDig
    SkillTypeKnapping
    SkillTypeChop
    SkillTypeFish
    VerbTypeEatCookedFishFilet
    VerbTypeEatCookedGrub
    VerbTypeAddFuelCookingFireCharcoal
    VerbTypeAddFuelCookingFireLog
    VerbTypeAddFuelCookingFirePlank
    VerbTypeAddFuelCookingFireStick
    VerbTypeAddFuelFurnaceCharcoal
    ItemTypeRockFlake
End Enum
