Public Enum Topic
    NavigationMove
    NavigationInventory
    NavigationVerb
    NavigationDeeds
    NavigationGameMenu
    NavigationSkills
    VerbTypeForage
    VerbTypeCraft
    VerbTypeChop
    VerbTypeDig
    VerbTypeEatGrub
    VerbTypeAddFuel
    VerbTypeWait
    VerbTypeFish
    VerbTypeEatFish
    ItemTypePlantFiber
    ItemTypeStick
    ItemTypeRock
    ItemTypeTwine
    ItemTypeSharpRock
    ItemTypeHatchet
    ItemTypeLog
    ItemTypeHammer
    ItemTypePlank
    ItemTypeSharpStick
    ItemTypeGrub
    ItemTypeCookingFire
    ItemTypeCookedGrub
    ItemTypeClay
    ItemTypeCharcoal
    ItemTypeUnfiredBrick
    ItemTypeBrick
    ItemTypeFishingNet
    ItemTypeRawFish
    ItemTypeRawFishFilet
    ItemTypeFishHead
    ItemTypeFishGuts
    ItemTypeKnife
    ItemTypeBlade
    ItemTypeCookedFishFilet
    ItemTypeFurnace
    RecipeTypeTwine
    RecipeTypeSharpRock
    RecipeTypeSharpStick
    RecipeTypeHatchet
    RecipeTypeHammer
    RecipeTypePlank
    RecipeTypeCookingFire
    RecipeTypeFurnace
    RecipeTypeCharcoalCookingFire
    RecipeTypeCookedGrub
    RecipeTypeCookedFishFilet
    RecipeTypeUnfiredBrick
    RecipeTypeKnife
    RecipeTypeBlade
    RecipeTypeRawFishFilet
    RecipeTypeFishingNet
    RecipeTypeBrick
End Enum
