Public Class GameState
    Public Const Neutral = "Neutral"
    Public Const Navigation = "Navigation"
    Public Const GameMenu = "GameMenu"
    Public Const Dead = "Dead"
    Public Const Inventory = "Inventory"
    Public Const ItemStack = "ItemStack"
    Public Const VerbMenu = "VerbMenu"
    Public Const Deeds = "Deeds"
    Public Const SkillMenu = "SkillMenu"
    Public Const SaveMenu = "SaveMenu"
    Public Const LoadMenu = "LoadMenu"
    Public Const Topic = "Topic"
    Public Const Map = "Map"
    Public Const Statistics = "Statistics"
    Public Const Dialog = "Dialog"
End Class
