Public Enum RecipeType
    AddFuelCookingFireStick
    AddFuelCookingFirePlank
    AddFuelCookingFireLog
    AddFuelCookingFireCharcoal
    AddFuelFurnaceCharcoal
    Blade
    Brick
    CharcoalCookingFire
    Chop
    CookedFishFilet
    CookedGrub
    CookingFire
    DigGrass
    DigPond
    EatCookedFishFilet
    EatCookedGrub
    Fish
    FishingNet
    ForageGrass
    ForagePine
    ForageRock
    Furnace
    Hammer
    Hatchet
    Knife
    Plank
    RawFishFilet
    SharpRock
    SharpStick
    Twine
    UnfiredBrick
    Wait
End Enum
