//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEditor.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitmapPixel
    {
        public int BitmapPixelId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int ColorId { get; set; }
        public int BitmapId { get; set; }
    
        public virtual Bitmap Bitmap { get; set; }
    }
}
