//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEditor.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitmap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bitmap()
        {
            this.BitmapPixels = new HashSet<BitmapPixel>();
        }
    
        public int BitmapId { get; set; }
        public int BitmapWidth { get; set; }
        public int BitmapHeight { get; set; }
        public int BitmapSequenceId { get; set; }
        public int BitmapIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitmapPixel> BitmapPixels { get; set; }
        public virtual BitmapSequence BitmapSequence { get; set; }
    }
}
