//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEditor.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glyph
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glyph()
        {
            this.GlyphPixels = new HashSet<GlyphPixel>();
        }
    
        public int GlyphId { get; set; }
        public int GlyphCharacter { get; set; }
        public int FontId { get; set; }
        public int GlyphWidth { get; set; }
    
        public virtual Font Font { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlyphPixel> GlyphPixels { get; set; }
    }
}
