export const StatisticType = {
    SATIETY: "SATIETY",
    MAXIMUM_SATIETY: "MAXIMUM_SATIETY",
    HEALTH: "HEALTH",
    MAXIMUM_HEALTH: "MAXIMUM_HEALTH",
    DURABILITY: "DURABILITY",
    MAXIMUM_DURABILITY: "MAXIMUM_DURABILITY",
    FUEL: "FUEL",
    FORAGING: "FORAGING",
    DIGGING: "DIGGING",
    CHOPPING: "CHOPPING",
    FISHING: "FISHING"
}
Object.freeze(StatisticType);
