//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFontImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlyphPixel
    {
        public int GlyphPixelId { get; set; }
        public int GlyphId { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    
        public virtual Glyph Glyph { get; set; }
    }
}
