Public Enum TerrainType
    None
    Black
    DarkGray
    LightGray
    White
    BrickWallNorth
    BrickWallEast
    BrickWallSouth
    BrickWallWest
    BrickWallNortheastInsideCorner
    BrickWallSoutheastInsideCorner
    BrickWallSouthwestInsideCorner
    BrickWallNorthwestInsideCorner
    BrickWallNortheastOutsideCorner
    BrickWallSoutheastOutsideCorner
    BrickWallSouthwestOutsideCorner
    BrickWallNorthwestOutsideCorner
    BrickDoorwayNorth
    BrickDoorwayEast
    BrickDoorwaySouth
    BrickDoorwayWest
    LadderUp
    LadderDown
    Bed
    Crate
    FenceNorth
    FenceEast
    FenceSouth
    FenceWest
    FenceNortheast
    FenceSoutheast
    FenceSouthwest
    FenceNorthwest
    LightBlockWall
    LightBlockDoorway
    LightBlockWindow
    LightBlockSign
    DarkBlockWall
    DarkBlockDoorway
    DarkBlockWindow
    DarkBlockSign
    LightBlockRoofWest
    LightBlockRoofEast
    LightBlockRoofCap
    DarkRoofWest
    DarkRoofEast
    DarkRoofCap
    DarkRoofCenterline
    LightBlockBattlement
    DarkBlockRoofWest
    DarkBlockRoofEast
    DarkBlockRoofCap
    LightRoofWest
    LightRoofEast
    LightRoofCap
    LightRoofCenterline
    DarkBlockBattlement
    LightPath
    MediumPath
    DarkPath
    LightRoad
    MediumRoad
    DarkRoad
    GoodChurch
    EvilChurch
    LightBlockArchWindow
    DarkBlockArchWindow
    Water
    SignPost
    Town
    BattlementShadow
    RESERVED1
    RESERVED2
    PanelNorth
    PanelEast
    PanelSouth
    PanelWest
    PanelNortheast
    PanelSoutheast
    PanelSouthwest
    PanelNorthwest
    PanelNorthDoorway
    PanelEastDoorway
    PanelSouthDoorway
    PanelWestDoorway
    CounterVertical
    CounterSouthwest
    CounterHorizontal
    CounterSoutheast
    Table
    WestChair
    EastChair
    Bookcase
    Stairs1
    Stairs2
End Enum
