//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseBitmapSequenceImporter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOWDEntities : DbContext
    {
        public TOWDEntities()
            : base("name=TOWDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitmap> Bitmaps { get; set; }
        public virtual DbSet<BitmapSequence> BitmapSequences { get; set; }
        public virtual DbSet<BitmapPixel> BitmapPixels { get; set; }
    }
}
